
//==============================================================================
//
//   service_types.h 
//
//==============================================================================
//  arsscriptum - made in quebec 2020 <guillaumeplante.qc@gmail.com>
//==============================================================================


#ifndef __SERVICE_TYPES_H__
#define __SERVICE_TYPES_H__

#include "enum_to_string.h"


#ifdef __cplusplus
extern "C" {
#endif


#define GENERATE_ENUM_STRINGS  // Start string generation

	/*
typedef enum _mps_agent_version_t
{
	CCC_AGENT_VERSION_1_0 = CORE_MAKE_VERSION(1, 0),                // version 1.0
	CCC_AGENT_VERSION_1_1 = CORE_MAKE_VERSION(1, 1),                // version 1.1
	CCC_AGENT_VERSION_1_2 = CORE_MAKE_VERSION(1, 2),                // version 1.2
	CCC_AGENT_VERSION_CURRENT = CORE_MAKE_VERSION(1, 2),    // latest known version
} mps_agent_version_t;
*/

	BEGIN_ENUM(CCC_ERRORS)
	{
		DECL_ENUM_ELEMENT(CCC_NO_ERROR)		//  0
			, DECL_ENUM_ELEMENT(CCC_ERROR_START)	// -1
	}
	END_ENUM(CCC_ERRORS)

		BEGIN_ENUM(CCC_CONTROL)
	{
		DECL_ENUM_ELEMENT(CCC_CONTROL_UNKNOWN)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_STOP)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_PAUSE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_CONTINUE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_INTERROGATE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_SHUTDOWN)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_PARAMCHANGE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_NETBINDADD)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_NETBINDREMOVE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_NETBINDENABLE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_NETBINDDISABLE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_DEVICEEVENT)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_HARDWAREPROFILECHANGE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_POWEREVENT)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_SESSIONCHANGE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_PRESHUTDOWN)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_CTRL_BREAK)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_CTRL_C)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_CTRL_CLOSE)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_CTRL_LOGOFF)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_CTRL_SHUTDOWN)
			, DECL_ENUM_ELEMENT(CCC_CONTROL_CTRL_UNKNOWN)
	}
	END_ENUM(CCC_CONTROL)


		enum CCC_CURRENT_STATES {
		CCC_CURRENT_STATE_UNKNOWN = 0x00000000
		, CCC_CURRENT_STATE_STOPPED = 0x00000001
		, CCC_CURRENT_STATE_START_PENDING = 0x00000002
		, CCC_CURRENT_STATE_STOP_PENDING = 0x00000003
		, CCC_CURRENT_STATE_RUNNING = 0x00000004
		, CCC_CURRENT_STATE_CONTINUE_PENDING = 0x00000005
		, CCC_CURRENT_STATE_PAUSE_PENDING = 0x00000006
		, CCC_CURRENT_STATE_PAUSED = 0x00000007
	};

	enum CCC_ACCEPTED_CONTROLS {
		CCC_ACCEPTED_CONTROL_NONE = 0x00000000
		, CCC_ACCEPTED_CONTROL_STOP = 0x00000001
		, CCC_ACCEPTED_CONTROL_PAUSE_CONTINUE = 0x00000002
		, CCC_ACCEPTED_CONTROL_SHUTDOWN = 0x00000004
		, CCC_ACCEPTED_CONTROL_PARAMCHANGE = 0x00000008
		, CCC_ACCEPTED_CONTROL_NETBINDCHANGE = 0x00000010
		, CCC_ACCEPTED_CONTROL_HARDWAREPROFILECHANGE = 0x00000020
		, CCC_ACCEPTED_CONTROL_POWEREVENT = 0x00000040
		, CCC_ACCEPTED_CONTROL_SESSIONCHANGE = 0x00000080
		, CCC_ACCEPTED_CONTROL_PRESHUTDOWN = 0x00000100
	};

	enum CCC_CUSTOM_MESSAGE {
		CCC_CONTROL_CTRL_USERDEFINED = 0x10000000
	};


	enum CCC_LOG_TYPES {
		CCC_LOG_SUCCESS
		, CCC_LOG_ERROR_TYPE
		, CCC_LOG_WARNING_TYPE
		, CCC_LOG_INFORMATION_TYPE
		, CCC_LOG_AUDIT_SUCCESS
		, CCC_LOG_AUDIT_FAILURE
	};

	enum CCC_EXECUTION_MODE {
		SC_MODE_BARE = 0
		, SC_MODE_OFFLINE_LOCAL_MONITOR
		, SC_MODE_SERVER
		, SC_MODE_TEST
	};

	typedef struct {
		CCC_CURRENT_STATES    CurrentState;
		CCC_ACCEPTED_CONTROLS AcceptedControls;
		long                      ExitCode;
		long                      BGPSpecificExitCode;
		long                      CheckPoint;
		long                      ExpectedTimeMillisecs;
	} CCC_STATUS;


	enum CCC_RETURN_CODES {
		CCC_RETURN_CODE_SUCCESS
		, CCC_RETURN_CODE_MINOR_ERROR
		, CCC_RETURN_CODE_DEBUGGER_DETECTED
	};

#undef GENERATE_ENUM_STRINGS   // Stop string generation 

#ifdef __cplusplus
}
#endif




#endif//__SERVICE_TYPES_H__